routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('unidades','UnidadeController');
Route::resource('dentistas','DentistaController');
Route::resource('horarios','HorarioController');
Route::resource('newsletters','NewsletterController');

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" rel="stylesheet">
    <link href="{{ url('/css/layout.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]);?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                           {{ config('app.name', 'Laravel') }} 
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
    
                    <ul class="nav navbar-nav navbar-right">

                        <li><a href="{{ url('/unidades') }}">Unidades</a></li>
                        <li><a href="{{ url('/dentistas') }}">Dentistas</a></li>
                        <li><a href="{{ url('/horarios/create') }}">Horários</a></li>
                        <li><a href="{{ url('/newsletters') }}">Importação</a></li>                        
                    </ul>
                </div>
            </div>
        </nav>
        @if (count($errors) > 0)
                @foreach ($errors->all() as $error)
                    <div class="alert alert-warning" role="alert">{{ $error }}</div>
                @endforeach
        @endif
        @yield('content')
        <hr>

        <!-- Footer -->
        <footer>
            <div class="col-lg-12">
                <p>Copyright &copy; BlueDental</p>
            </div>
        </footer>        
    </div>
</body>
</html>

resources/views/dentistas.blade.php
@extends('app')
@section('content')
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h2>Dentistas</h2>
                    <a href="{{ url('/dentistas/create') }}">
                        <button class="btn btn-primary">Cadastrar Dentista</button>
                    </a>
              </div>
            <div>
            <br>
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    @if(count($dentistas) > 0)
                        <table class="table">
                            <tread>
                                <tr>
                                    <th>Nome</th>
                                    <th>Email</th>
                                    <th>Visualizar Horários</th>
                                    <th>Excluir</th>
                                </tr>
                            </tread>
                        @foreach ($dentistas as $dentista)
                            <tr>
                                <td>{{$dentista->nome}}</td>
                                <td>{{$dentista->email}}</td>
                                <td><a href="{{ route('dentistas.show', $dentista->id) }}">Visualizar</a></td>
                                <td>
                                    <form action="{{ route('dentistas.destroy', $dentista->id) }}" method="POST">
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                        <button>Apagar</button>
                                    </form>                                
                                </td>
                            </tr>
                        @endforeach
                        </table>
                    @else
                        <h3>Não existem dentistas cadastrados</h3>
                    @endif
                </div>
            </div>
        </div>
@endsection

resources/views/home.blade.php
@extends('app')
@section('content')
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                        <h3>BlueDental - Bem-Vindo!</h3>
                </div>
            </div>
        </div>
@endsection

resources/views/newsletters.blade.php
@extends('app')
@section('content')
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h2>Newsletter</h2>
                    <a href="{{ url('/newsletters/create') }}">
                        <button class="btn btn-primary">Importar Registros</button>
                    </a>
              </div>
            <div>
            <br>
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    @if(count($newsletterClients) > 0)
                        <table class="table">
                            <tread>
                                <tr>
                                    <th>Nome</th>
                                    <th>Email</th>
                                </tr>
                            </tread>
                        @foreach ($newsletterClients as $newsletterClient)
                            <tr>
                                <td>{{$newsletterClient->nome}}</td>
                                <td>{{$newsletterClient->email}}</td>
                            </tr>
                        @endforeach
                        </table>
                    @else
                        <h3>Não existem registros importados</h3>
                    @endif
                </div>
            </div>
        </div>
@endsection

resources/views/unidades.blade.php
@extends('app')
@section('content')
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h2>Unidades</h2>
                    <a href="{{ url('/unidades/create') }}">
                        <button class="btn btn-primary">Cadastrar Unidade</button>
                    </a>
              </div>
            <div>
            <br>
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    @if(count($unidades) > 0)
                        <table class="table">
                            <tread>
                                <tr>
                                    <th>Descrição</th>
                                    <th>Excluir</th>
                                </tr>
                            </tread>
                        @foreach ($unidades as $unidade)
                            <tr>
                                <td>{{$unidade->descricao}}</td>
                                <td>
                                    <form action="{{ route('unidades.destroy', $unidade->id) }}" method="POST">
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                        <button>Apagar</button>
                                    </form>                                
                                </td>
                            </tr>
                        @endforeach
                        </table>
                    @else
                        <h3>Não existem unidades cadastradas</h3>
                    @endif
                </div>
            </div>
        </div>
@endsection