routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Route::resource('unidades','UnidadeController');
Route::resource('dentistas','DentistaController');
Route::resource('horarios','HorarioController');
Route::resource('newsletters','NewsletterController');

app/Dentista.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dentista extends Model
{
    //
    protected $fillable = ['nome','email'];
}

app/Http/Controllers/DentistaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Dentista;
use App\Horarios;

class DentistaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $dentistas = Dentista::all();
    
        return view('dentistas',['dentistas' => $dentistas ]);        	
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('dentistas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate( $request,[   
                'nome' => 'required|max:100',
                'email' => 'required|email|max:255|unique:dentistas',
            ]);
        
        $dados = $request->all();
        
        if(Dentista::create($dados))
        {
            return redirect('dentistas');
        }else
        {
            return view('dentistas.create',['errors' => array('Não foi possível cadastrar o novo dentista')]);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $horarios = DB::table('dentistas')
        ->join('horarios','dentistas.id','=','horarios.dentista_id')
        ->join('unidades','horarios.unidade_id','=','unidades.id')
        ->where('horarios.dentista_id',$id)
        ->select('unidades.descricao','horarios.dia','horarios.horario_inicio','horarios.horario_termino','horarios.id','dentistas.nome')
        ->get();

        return view('dentistas.horarios',['horarios' => $horarios]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Dentista::destroy($id);
        return redirect('dentistas');
    }
}

resources/views/dentistas/create.blade.php
@extends('app')
@section('content')
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-heading">Novo Dentista</div>
                            <div class="panel-body">
                                @if (count($errors) > 0)
                                        @foreach ($errors->all() as $error)
                                            <div class="alert alert-warning" role="alert">{{ $error }}</div>
                                        @endforeach
                                @endif

                                {!! Form::open(['url' => 'dentistas','method'=>'post']) !!}
                                    <div class="form-group">
                                        {!! Form::label('nome','Nome') !!}
                                        {!! Form::text('nome','',['class' => 'form-control','placeholder' => 'nome']) !!}

                                        @if ($errors->has('nome'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('nome') }}</strong>
                                            </span>
                                        @endif
                                    </div>
                                    <div class="form-group">
                                        {!! Form::label('email','Email') !!}
                                        {!! Form::text('email','',['class' => 'form-control','placeholder' => 'email']) !!}

                                        @if ($errors->has('email'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('email') }}</strong>
                                            </span>
                                        @endif
                                    </div>

                                    <div class="form-group">
                                        {!! Form::submit('Cadastrar',['class' => 'btn btn-default']) !!}
                                    </div>
                                {!! Form::close() !!}		
                            </div>
                    </div>
                </div>		
            </div>
            
        </div>
@endsection

resources/views/dentistas/horarios.blade.php
@extends('app')
@section('content')
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h2>Horários</h2>
                    <a href="{{ url('/horarios/create') }}">
                        <button class="btn btn-primary">Cadastrar horário</button>
                    </a>
              </div>
            <div>
            <br>
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    @if(count($horarios) > 0)
                        <table class="table">
                            <tread>
                                <tr>
                                    <th>Unidade</th>
                                    <th>Dia</th>
                                    <th>Início</th>
                                    <th>Término</th>
                                    <th>Excluir Horário</th>
                                </tr>
                            </tread>
                        @foreach ($horarios as $horario)
                            <tr>
                                <td>{{$horario->descricao}}</td>
                                <td>{{$horario->dia}}</td>
                                <td>{{$horario->horario_inicio}}</td>
                                <td>{{$horario->horario_termino}}</td>
                                <td>
                                    <form action="{{ route('horarios.destroy', $horario->id) }}" method="POST">
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                        <button>Apagar</button>
                                    </form>                                
                                </td>
                            </tr>
                        @endforeach
                        </table>
                    @else
                        <h3>Não existem horários cadastrados para este dentista</h3>
                    @endif
                </div>
            </div>
        </div>
@endsection